services:
  app:
    image: catalyst-apim-service:0.0.0
    container_name: catalyst-apim-service-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: development
    volumes:
      - ../:/src
    user: "appuser"
    tty: true
