# Python 3.11
FROM python:3.11-bookworm AS base

RUN apt-get update
RUN apt-get install -y curl git

ARG USERNAME=appuser
RUN useradd --create-home $USERNAME

USER $USERNAME

WORKDIR /src

COPY . .

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="${PATH}:/home/${USERNAME}/.local/bin"
RUN poetry config virtualenvs.in-project true

# Development
FROM base AS development

USER root
RUN apt-get install -y git

